version: "3.7"

####################### Services Definition #######################
services:
  server:
    container_name: server
    image: server:test
    build:
      context: .
      dockerfile: Dockerfile.server
      target: "test"
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    depends_on:
      - database
    networks:
      - default

  database:
    container_name: database
    image: database:test
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: bridge
