version: "3.7"

####################### Services Definition #######################
services:

  server-prod:
    container_name: server_prod
    image: server:prod
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DATABASE_URL=mongodb://admin:password@database_prod:27017/prod_db
    depends_on:
      - database-prod
    networks:
      - default

  database-prod:
    container_name: database_prod
    image: mongo:3.6
    volumes:
      - "db-data:/data/db"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=prod_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: bridge

####################### Volumes Definition ########################
volumes:
  db-data:
    driver: local
