version: "3.7"

####################### Services Definition #######################
services:

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DATABASE_URL=mongodb://admin:password@database:27017/dev_db?authSource=admin
    depends_on:
      - database
    networks:
      - default

  database:
    container_name: database
    image: mongo:3.6
    volumes:
      - "db-data:/data/db"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=dev_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: bridge

####################### Volumes Definition ########################
volumes:
  db-data:
    driver: local
